context:
  version: "6.0.0"

package:
  name: del-cli
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/del-cli/-/del-cli-${{ version }}.tgz
  sha256: 117da7402933ef52f3de0eb85459424655dcbfe8fa46ce45ddd3d819dbf50f89

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
  run:
    - nodejs

tests:
  - script:
      - del-cli --help

about:
  license: MIT
  license_file: license
  summary: Delete files and directories
  homepage: https://github.com/sindresorhus/del-cli
  repository: https://github.com/sindresorhus/del-cli

extra:
  recipe-maintainers:
    - danielnachun
