context:
  version: "8.0.1"

package:
  name: del-cli
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/del-cli/-/del-cli-${{ version }}.tgz
  sha256: 1c0853c25ad793601497e8d9aeb7e00985f25415968af5b27bc3e5fab03a553f

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
  run:
    - nodejs

tests:
  - script:
      - del-cli --help

about:
  license: MIT
  license_file: license
  summary: Delete files and directories
  homepage: https://github.com/sindresorhus/del-cli
  repository: https://github.com/sindresorhus/del-cli

extra:
  recipe-maintainers:
    - danielnachun
